### ISSUE TITLE
Missing requirements.txt in Hierarchical-Localization

### ISSUE THREAD

**Issue by abhishek47kashyap** [GradientSpaces/LoopSplat#1]
After setting up the conda environment with all dependencies specified in `environment.yml`, I tried to follow the instructions to install _hloc_, however `python -m pip install -e .` errors out:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/abhishek/Code/LoopSplat/thridparty/Hierarchical-Localization/requirements.txt'
```
Seems like `requirements.txt` is absent?

Also, a really minor typo `thrid` in the directory name `thridparty/Hierarchical-Localization` :)

**Comment by unique1i** [comment]
Hi @abhishek47kashyap, thanks for your spot! I uploaded the missing requirements.txt and renamed the folder.

**Comment by Zhu-Liyuan** [comment]
I have fixed the submodule problem. Now it's working on my machine. I close this issue for now.
