### ISSUE TITLE
faiss-gpu: assert hasattr(self, 'getDevice'), 'GPU tensor on CPU index not allowed'

### ISSUE THREAD

**Issue by xuquanfeng** [GradientSpaces/LoopSplat#12]
Due to the Faiss package, I cannot run apartment dataset completely.
![微信图片_20241110180928](https://github.com/user-attachments/assets/17917c3a-c865-47c9-9f50-71314f613e03)

**Comment by Zhu-Liyuan** [comment]
Hi, it might be a hardware-related issue. Can you try the solution at https://github.com/GradientSpaces/LoopSplat/issues/5?
