### ISSUE TITLE
How to get "undistorted_depths" from scannet++?

### ISSUE THREAD

**Issue by ZoranGong** [GradientSpaces/LoopSplat#14]
hi, 
I'm trying to reproduce your impressive work on scannet++ but I notice that **"undistorted_depths"** is needed in your dataset.py.
Following the official documents of scannet++, I can only get **"undistorted_images"** and **"transforms_undistorted.json"**. 

So, can you explain to me how to get **"undistorted_depths"** in detail?

Thanks for your help!

**Comment by unique1i** [comment]
Hi, we used the script [here](https://github.com/Nik-V9/scannetpp) from SplaTAM authors for undistorted_depths.

**Comment by ZoranGong** [comment]
thanks for your quick response! I got "undistorted_depths" finally. It's really helpful!
