### ISSUE TITLE
Gaussian merging

### ISSUE THREAD

**Issue by lizhiteng111** [GradientSpaces/LoopSplat#15]
Hello, first of all, thank you for your excellent work. I have a question regarding the final submap merging process. I noticed that you opted to extract the point cloud from the obtained mesh for merging the submaps, rather than merging the Gaussian point clouds. If it's not too much trouble, could you kindly share the reasoning behind this decision?

**Comment by Zhu-Liyuan** [comment]
Hi,
Thank you for your interest in our work. Simply merging by concatenating all Gaussians in each submap will lead to rendering artifacts at the overlapping region (overly dense Gaussians). We, therefore, downsample a new Gaussian point cloud from all submaps and re-optimize the global map using all the keyframes. I hope this addresses your question.
