### ISSUE TITLE
Failed to get reasonable results on ScanNet

### ISSUE THREAD

**Issue by XXXCARREY** [GradientSpaces/LoopSplat#18]
Thank you for your amazing work! I encountered a problem while reproducing LoopSplat on ScanNet. During tracking, the camera error rapidly increases, eventually leading to tracking failure. As shown in the picture, the values are still relatively normal in Tracking frame 3, but issues arise in Tracking frame 4. Have you experienced this issue, and how can it be resolved? I have already processed the dataset in advance using `scannet_preprocess.ipynb`.
`
![image](https://github.com/user-attachments/assets/415c2be2-b76d-47bb-9443-7e57dd9d5d0f)

**Comment by unique1i** [comment]
Hi, thanks for the feedback. We haven't noticed the spike of error, can you provide which scannet scene is this?

**Comment by XXXCARREY** [comment]
Sorry, I found that only the results on the ScanNet scenes had issues, while the other datasets are normal. Therefore, I generated and processed ScanNet again, and the problem has now been resolved. Thank you very much for your quick response.
