### ISSUE TITLE
Slow speed on ScanNet

### ISSUE THREAD

**Issue by laliwang** [GradientSpaces/LoopSplat#4]
Thanks for your excellent work and sharing! When I try to reproduce the slam process on scene0181 of ScanNet, I found that the optimization costs quite a long time, for nearly 4 hours on 2337 frames. What's more, the reconstruction evaluation also takes a long time as follows. 
![image](https://github.com/user-attachments/assets/126bb70b-d944-427b-8562-2d9895d81d3c)
My device is **NVIDIA L40** with cuda-toolkit-11.8. Is it normal that the optimization speed and mesh extraction speed are so slow? Thanks!

**Comment by Zhu-Liyuan** [comment]
Thank you for your interest in our work and running our code. For your questions:

- Long runtime on Scannet: we built a SLAM system that purely uses 3DGS for tracking, mapping and global consistency. The iterative nature of optimization makes the system less efficient. We did not focus on improving system efficiency in this work and left it for future work. For example, the speed can be enhanced with multi-thread processing and less loop closures.
- For the reconstruction, we use open3d to extract the mesh. So it is normal for reconstruction evaluation to take this long.
