### ISSUE TITLE
Are there any results on large TUM dataset such as fr2_pioneer_360?

### ISSUE THREAD

**Issue by WeiguangHan** [GradientSpaces/LoopSplat#8]
I tested the accuracy of MonoGS using large TUM data sequences such as fr2_pioneer_360. However, there was a significant accuracy error. So I want to know if LoopSplat has tackled this problem?

**Comment by Zhu-Liyuan** [comment]
Thank you for your interest. We didn't test LoopSplat on fr2_pioneer_360. You can give it a try.
